version: "3.5"

services:
  pingfederate:
    image: pingidentity/pingfederate:latest
    command: wait-for pingdirectory:389 -t 600 -- entrypoint.sh start-server
    env_file:
      - ./env-vars
    secrets:
      - devops-secret
    environment:
    - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
    - SERVER_PROFILE_PATH=pingfederate
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999

  pingdirectory:
    image: pingidentity/pingdirectory:latest
    env_file:
      - ./env-vars
    secrets:
      - devops-secret
    environment:
    - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
    - SERVER_PROFILE_PATH=pingdirectory
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 389:389
      - 1636:636
      - 2443:2443

  pingdatasync:
    image: pingidentity/pingdatasync:latest
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
      - SERVER_PROFILE_PATH=pingdatasync
    env_file:
      - ./env-vars   
    secrets:
      - devops-secret
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdatasync:/opt/out
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 3636:636
      - 3443:443
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    ports:
      - 8080:8080
      - 8443:8443

  pingconfig:
    image: pricecs/pingconfigurator
    environment:
      # Collections: Solution - Customer360 v2.0.0
      - COLLECTIONS=https://www.getpostman.com/collections/f1f5ffff5ddd891e720d
    volumes: 
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./postman_vars.json:/usr/src/app/postman_vars.json  

  pingcentral:
    image: pingidentity/pingcentral:latest
    command: wait-for pingfederate:9031 -t 7200 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/Customer360.git
      - SERVER_PROFILE_PATH=pingcentral/external-mysql-db
    env_file:
      - ./env-vars
    secrets:
      - devops-secret
    ports:
      - "9022:9022"
    depends_on:
      - "pingcentral-db"

  pingcentral-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 2Federate
    ports:
      - "3306:3306"

secrets:
  devops-secret:
    file: ${HOME}/.pingidentity/devops