apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: pingdatasync
  name: pingdatasync
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pingdatasync
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
        kompose.version: 1.21.0 ()

      labels:
        io.kompose.service: pingdatasync
    spec:
      containers:
      - env:
        - name: PING_IDENTITY_ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              key: PING_IDENTITY_ACCEPT_EULA
              name: env-vars
        - name: SERVER_PROFILE_PATH
          value: pingdatasync
        - name: SERVER_PROFILE_URL
          value: https://github.com/pingidentity/pingidentity-solutions-sa-ciam-demo.git
        - name: USER_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: USER_BASE_DN
              name: env-vars
        image: pingidentity/pingdatasync:edge
        imagePullPolicy: "IfNotPresent"
        name: pingdatasync
        ports:
        - containerPort: 636
        - containerPort: 443
        resources: {}
        envFrom:
          - secretRef:
              name: devops-secret
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: pingdatasync
  name: pingdatasync
spec:
  ports:
  - name: "636"
    port: 636
    targetPort: 636
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: pingdatasync
status:
  loadBalancer: {}
