apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingcentral-db
  name: pingcentral-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pingcentral-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: pingcentral-db
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 2Federate
        image: mysql
        imagePullPolicy: "IfNotPresent"
        name: pingcentral-db
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingcentral-db
  name: pingcentral-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: pingcentral-db
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingcentral
  name: pingcentral
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pingcentral
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: pingcentral
    spec:
      containers:
      - args:
        - wait-for
        - pingfederate:9031
        - -t
        - "7200"
        - --
        - entrypoint.sh
        - start-server
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: env-vars
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env-vars
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: env-vars
        - name: ADMIN_CLIENT_ISSUER
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_ISSUER
              name: env-vars
        - name: PING_CENTRAL_BLIND_TRUST
          valueFrom:
            configMapKeyRef:
              key: PING_CENTRAL_BLIND_TRUST
              name: env-vars
        - name: ADMIN_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_ID
              name: env-vars
        - name: ADMIN_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_SECRET
              name: env-vars
        - name: PING_CENTRAL_OIDC_ENABLED
          valueFrom:
            configMapKeyRef:
              key: PING_CENTRAL_OIDC_ENABLED
              name: env-vars
        - name: PING_CENTRAL_VERIFY_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: PING_CENTRAL_VERIFY_HOSTNAME
              name: env-vars
        - name: PING_IDENTITY_ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              key: PING_IDENTITY_ACCEPT_EULA
              name: env-vars
        - name: PING_CENTRAL_LOG_LEVEL
          value: DEBUG
        - name: SERVER_PROFILE_PATH
          value: pingcentral/external-mysql-db
        - name: SERVER_PROFILE_URL
          value: https://github.com/pingidentity/Customer360.git
        - name: USER_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: USER_BASE_DN
              name: env-vars
        image: pingidentity/pingcentral
        imagePullPolicy: "IfNotPresent"
        name: pingcentral
        ports:
        - containerPort: 9022
        resources: {}
        envFrom:
          - secretRef:
              name: devops-secret
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingcentral
  name: pingcentral
spec:
  ports:
  - name: "9022"
    port: 9022
    targetPort: 9022
  selector:
    io.kompose.service: pingcentral
status:
  loadBalancer: {}
