apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingdirectory
  name: pingdirectory
spec:
  ports:
  - name: "389"
    port: 389
    targetPort: 389
  - name: "1636"
    port: 1636
    targetPort: 636
  - name: "443"
    port: 443
    targetPort: 443
  - name: "2443"
    port: 2443
    targetPort: 2443
  selector:
    io.kompose.service: pingdirectory
status:
  loadBalancer: {}
